[package]
name = "ble-rpizero-jinou-test"
version = "0.1.0"
authors = ["banoss"]
edition = "2018"

[dependencies]
blurz = "0.4.0"
lazy_static = "1.4.0"
regex = "1.4.2"
log = "0.4.11"
env_logger = "0.8.2"
sscanf = "0.2.1"